### ISSUE TITLE
[Bug] [Frontend] Bug on main page

### ISSUE THREAD

**Issue by dangvuthang** [dangvuthang/rocodingtest#29]
### Description

- Inconsistent `font` used by logo (Too many font-family loaded during initial page load caused the logo falls back on other font)

![Screenshot (569)](https://user-images.githubusercontent.com/43143636/160847698-c71c9f39-87d4-4d48-a5a3-cbd7a07adeb3.png)

- `lottie-player` causes issue when built

![Screenshot (568)](https://user-images.githubusercontent.com/43143636/160847489-85b501ef-7d97-4b47-b3b4-d5a6e88bb1bb.png)

**Comment by nhannguyentruc214** [comment]
Logo is **fixed** by removing variant = "body1"

Lottieplayer **fixed** :
 - Added: **declaration.d.ts** file

**Comment by dangvuthang** [comment]
> Logo is **fixed** by removing variant = "body1"
> 
> Lottieplayer **fixed** :
> 
> * Added: **declaration.d.ts** file

Please make a new branch to fix the problem and tag me as a reviewers when you are done. Thank you
